# -*- coding: utf-8 -*-

from odoo import api, fields, models
from odoo.exceptions import UserError


class InclusiveFinancingContractTemplatePreview(models.TransientModel):
    _name = 'ifs.contract.template.preview'
    _description = 'Contract Template Preview'
    _inherit = ['mail.render.mixin']
    _CONTRACT_TEMPLATE_FIELDS = ['body_html', ]

    @api.model
    def _selection_target_model(self):
        return [(model.model, model.name) for model in self.env['ir.model'].sudo().search([])]

    @api.model
    def _selection_languages(self):
        return self.env['res.lang'].get_installed()

    @api.model
    def default_get(self, fields):
        result = super(InclusiveFinancingContractTemplatePreview,
                       self).default_get(fields)
        if not result.get('contract_template_id') or 'resource_ref' not in fields:
            return result
        contract_template = self.env['ifs.contract.template'].browse(
            result['contract_template_id'])
        model = contract_template.model_id.sudo().model
        res = self.env[model].search([], limit=1)
        if res:
            result['resource_ref'] = '%s,%s' % (model, res.id)
        return result

    contract_template_id = fields.Many2one(
        'ifs.contract.template', string='关联合同模板', required=True)
    model_id = fields.Many2one(
        'ir.model', string='目标模型', related="contract_template_id.model_id")
    resource_ref = fields.Reference(
        string='记录', selection='_selection_target_model')
    lang = fields.Selection(_selection_languages,
                            string='模板预览语言')
    no_record = fields.Boolean('无记录', compute='_compute_no_record')
    error_msg = fields.Char('错误消息', readonly=True)
    body_html = fields.Html(
        '合同内容', compute='_compute_contract_template_fields', sanitize=False)
    # Extra fields info generated by generate_contract
    partner_ids = fields.Many2many(
        'res.partner', string='Recipients', compute='_compute_contract_template_fields')

    @api.depends('model_id')
    def _compute_no_record(self):
        for preview in self:
            preview.no_record = (self.env[preview.model_id.model].search_count(
                []) == 0) if preview.model_id else True

    @api.depends('lang', 'resource_ref')
    def _compute_contract_template_fields(self):
        """ Preview the mail template (body, subject, ...) depending of the language and
        the record reference, more precisely the record id for the defined model of the mail template.
        If no record id is selectable/set, the inline_template placeholders won't be replace in the display information. """
        copy_depends_values = {'lang': self.lang}
        contract_template = self.contract_template_id.with_context(lang=self.lang)
        try:
            if not self.resource_ref:
                self._set_contract_attributes()
            else:
                copy_depends_values['resource_ref'] = '%s,%s' % (
                    self.resource_ref._name, self.resource_ref.id)
                contract_values = contract_template.with_context(template_preview_lang=self.lang).generate_contract(
                    self.resource_ref.id, self._CONTRACT_TEMPLATE_FIELDS)
                self._set_contract_attributes(values=contract_values)
            self.error_msg = False
        except UserError as user_error:
            self._set_contract_attributes()
            self.error_msg = user_error.args[0]
        finally:
            # Avoid to be change by a invalidate_cache call (in generate_mail), e.g. Quotation / Order report
            for key, value in copy_depends_values.items():
                self[key] = value

    def _set_contract_attributes(self, values=None):
        for field in self._CONTRACT_TEMPLATE_FIELDS:
            field_value = values.get(
                field, False) if values else self.contract_template_id[field]
            self[field] = field_value
        self.partner_ids = values.get(
            'partner_ids', False) if values else False
