# -*- coding: utf-8 -*-

{
    'name': '进件流程',
    'version': '2.0',
    'description':
        """
鸥贝云进件流程
========================

鸥贝云的供应方、采购方进件及审批流程
        """,
    'summary': '鸥贝云进件流程管理',
    'author': 'Galaxy Team',
    'website': 'https://www.liefwiz.cn',
    'license': 'Other proprietary',
    'category': '鸥贝云/Partner',
    'sequence': 5,
    'depends': [
        'base',
        'mail',
        'galaxy_common',
        'galaxy_tdesign',
        'ifs_risk_manage',
        'ifs_gar_partner_relationship',
        'ifs_gar_invite',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/ifs_gar_entry_rules.xml',
        'data/ir_sequence_data.xml',
        'data/ifs_gar_entry_actions_server_data.xml',
        'data/ifs_gar_entry_definition_data.xml',
        'data/ifs_gar_entry_merchant_config_data.xml',
        'data/ifs_gar_entry_merchant_config_detail_data.xml',
        'data/ifs_message_cron.xml',
        'views/ifs_gar_entry_menu_views.xml',
        'views/ifs_gar_entry_supplier_views.xml',
        'views/ifs_gar_entry_franchisee_views.xml',
        'views/ifs_gar_entry_lawfirm_views.xml',
        'views/ifs_gar_entry_merchant_views.xml',
        'views/ifs_gar_invite_supplier_views.xml',
        'views/ifs_gar_invite_merchant_views.xml',
        'views/ifs_gar_invite_franchisee_views.xml',
        'views/ifs_gar_entry_merchant_config_views.xml',
        'views/res_config_settings_views.xml',
        'views/ifs_partner_supplier_views.xml',
        'views/ifs_partner_merchant_views.xml',
        'views/ifs_partner_franchisee_views.xml',
        'views/mobile_invite_franchisee_template.xml',
        'views/ifs_partner_lawfirm_views.xml',
        'views/ifs_message_views.xml',
        'views/ifs_gar_entry_merchant_credit_template.xml',
        'entry/ifs_gar_entry_step_views.xml',
        'entry/ifs_gar_entry_supplier_wizard_views.xml',
        'entry/ifs_gar_entry_supplier_cover_wizard_views.xml',
        'entry/ifs_gar_entry_supplier_base_info_wizard_views.xml',
        'entry/ifs_gar_entry_supplier_contact_wizard_views.xml',
        'entry/ifs_gar_entry_supplier_account_wizard_views.xml',
        'entry/ifs_gar_entry_supplier_doc_wizard_views.xml',
        'entry/ifs_gar_entry_supplier_finish_wizard_views.xml',
        'entry/ifs_gar_entry_franchisee_wizard_views.xml',
        'entry/ifs_gar_entry_franchisee_cover_wizard_views.xml',
        'entry/ifs_gar_entry_franchisee_base_info_wizard_views.xml',
        'entry/ifs_gar_entry_franchisee_contact_wizard_views.xml',
        'entry/ifs_gar_entry_franchisee_account_wizard_views.xml',
        'entry/ifs_gar_entry_franchisee_doc_wizard_views.xml',
        'entry/ifs_gar_entry_franchisee_finish_wizard_views.xml',
        'entry/ifs_gar_entry_lawfirm_wizard_views.xml',
        'entry/ifs_gar_entry_lawfirm_cover_wizard_views.xml',
        'entry/ifs_gar_entry_lawfirm_base_info_wizard_views.xml',
        'entry/ifs_gar_entry_lawfirm_contact_wizard_views.xml',
        'entry/ifs_gar_entry_lawfirm_account_wizard_views.xml',
        'entry/ifs_gar_entry_lawfirm_doc_wizard_views.xml',
        'entry/ifs_gar_entry_lawfirm_finish_wizard_views.xml',
        'entry/ifs_gar_entry_merchant_wizard_views.xml',
        'entry/ifs_gar_entry_merchant_cover_wizard_views.xml',
        'entry/ifs_gar_entry_merchant_base_info_wizard_views.xml',
        'entry/ifs_gar_entry_merchant_contact_wizard_views.xml',
        'entry/ifs_gar_entry_merchant_guarantor_wizard_views.xml',
        'entry/ifs_gar_entry_merchant_doc_wizard_views.xml',
        'entry/ifs_gar_entry_merchant_finish_wizard_views.xml',
        'wizard/ifs_gar_entry_supplier_selector_wizard_views.xml',
        'wizard/ifs_gar_entry_factor_selector_wizard_views.xml',
        'wizard/ifs_gar_entry_config_supplier_selector_wizard_views.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
    'assets': {
        'web.assets_backend': [
            'ifs_gar_entry/static/src/views/**/*',
            'ifs_gar_entry/static/src/scss/ifs_gar_entry.scss',
        ],
        'web.assets_frontend': [
            'ifs_gar_entry/static/src/js/partner_invite.js',
        ],
    }
}
