# -*- coding: utf-8 -*-

{
    'name': '鸥贝云合同管理',
    'version': '2.0',
    'description':
        """
鸥贝云产品的合同管理
===================================
鸥贝云项目的具体合同内容和签署的操作
        """,
    'summary': '管理鸥贝云业务相关的各项合同',
    'author': 'Inair Team',
    'website': 'https://www.liefwiz.cn',
    'license': 'Other proprietary',
    'category': '鸥贝云/Partner/Contract',
    'sequence': 12,
    'depends': [
        'base',
        'mail',
        'galaxy_common',
        'galaxy_tdesign',
        'ifs_partner_contract',
        # 'ifs_contract_sign_jzq',
        'ifs_gar_invite',
        'ifs_gar_entry',
        'ifs_gar_review',
        'ifs_gar_account',
        'ifs_gar_trade',
        'ifs_gar_repayment',
    ],
    'data': [
        'security/ifs_gar_contract_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/c10_contract_template.xml',
        'data/c10_contract_template_v2.xml',
        'data/c11_contract_template.xml',
        'data/c12_contract_template.xml',
        'data/c13_contract_template.xml',
        'data/c14_contract_template.xml',
        'data/d08_contract_template.xml',
        'data/f41_contract_template.xml',
        'data/f41_contract_template_v2.xml',
        'data/f42_contract_template.xml',
        'data/f42_contract_template_v2.xml',
        'data/t17_contract_template.xml',
        'data/t17_contract_template_v2.xml',
        'data/t18_contract_template.xml',
        'data/t18_contract_template_v2.xml',
        'data/t18a_contract_template_v2.xml',
        'data/t19_contract_template.xml',
        'data/t19_contract_template_v2b.xml',
        'data/t20_contract_template.xml',
        'data/t20_contract_template_v2b.xml',
        'data/t21_contract_template.xml',
        'data/t22_contract_template.xml',
        'data/t22_contract_template_v2.xml',
        'data/f43_contract_template.xml',
        'data/p01_contract_template.xml',
        'data/p02_contract_template.xml',
        'data/p10_contract_template.xml',
        'data/d09_contract_template.xml',
        'data/x10_contract_template.xml',
        'data/x11_contract_template.xml',
        'data/Z10_contract_template.xml',
        'data/Z20_contract_template.xml',
        # 'views/ifs_gar_invite_merchant_views.xml',
        'views/ifs_gar_invite_supplier_views.xml',
        'views/ifs_gar_invite_franchisee_views.xml',
        'views/ifs_gar_invite_lawfirm_views.xml',
        'views/ifs_gar_trade_order_views.xml',
        # 'views/ifs_gar_withdrawal_order_views.xml',
        # 'views/ifs_gar_loan_account_bill_views.xml',
        'views/ifs_contract_info_views.xml',
        'views/ifs_gar_entry_supplier_views.xml',
        'views/ifs_gar_entry_merchant_views.xml',
        'views/ifs_partner_supplier_views.xml',
        'views/ifs_partner_merchant_views.xml',
        'views/ifs_partner_supplier_views.xml',
        'views/ifs_gar_upgrade_quota_apply_views.xml',
        'views/ifs_partner_franchisee_views.xml',
        'views/ifs_gar_entry_franchisee_views.xml',
        'views/ifs_partner_lawfirm_views.xml',
        'views/ifs_gar_entry_lawfirm_views.xml',
        'wizard/ifs_gar_contract_sign_wizard_views.xml',
        'wizard/ifs_gar_invite_supplier_wizard_views.xml',
        'wizard/ifs_gar_invite_supplier_fee_wizard_views.xml',
        'wizard/ifs_gar_invite_supplier_contract_wizard_views.xml',
        'wizard/ifs_gar_invite_franchisee_wizard_views.xml',
        'wizard/ifs_gar_invite_franchisee_contract_wizard_views.xml',
        'wizard/ifs_gar_invite_lawfirm_wizard_views.xml',
        'wizard/ifs_gar_invite_lawfirm_contract_wizard_views.xml',
        'wizard/ifs_gar_trade_order_withdrawal_confirm_wizard_views.xml',
        'entry/ifs_gar_entry_supplier_contract_wizard_views.xml',
        'entry/ifs_gar_entry_merchant_contract_wizard_views.xml',
        'entry/ifs_gar_entry_merchant_guarantor_contract_wizard_views.xml',
        'entry/ifs_gar_entry_merchant_approval_info_wizard_views.xml',
        'entry/ifs_gar_entry_merchant_wizard_views.xml',
        'entry/ifs_gar_entry_supplier_wizard_views.xml',
        'entry/ifs_gar_entry_franchisee_contract_wizard_views.xml',
        'entry/ifs_gar_entry_franchisee_wizard_views.xml',
        'entry/ifs_gar_entry_lawfirm_contract_wizard_views.xml',
        'entry/ifs_gar_entry_lawfirm_wizard_views.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
    'assets': {
        'web.assets_qweb': [
            # 'ifs_template/static/src/webclient/**/*.xml',
        ],
        'web.assets_frontend': [
            'ifs_gar_contract/static/src/scss/ifs_gar_contract.scss',
        ],
        'web.assets_backend': [
            'ifs_gar_contract/static/src/scss/ifs_gar_contract.scss',
            'ifs_gar_contract/static/src/js/ifs_contract_sign.js',
            'ifs_gar_contract/static/src/js/sign_parent_handleNotification.js',
        ],
    }
}